### PR TITLE
Dedicated Rune Filtering Function

### PR DESCRIPTION
**Pull request by claytondaley**
Isolates logic for rune filtering in its own function.  Also defines and uses a configuration object (vs globals).

### CODE REVIEW

**Comment by claytondaley** [comment]
Crap.  Commit picked up wrong files.

**Comment by claytondaley** [comment]
I also notice I was modifying a `.Old` version.  I just followed the type hint for the method to it.

**Comment by Skibisky** [comment]
I moved it to old when I was doing some refactoring, I might still have plans to redo that filtering step, but right now all the build stuff uses it, so at least there is consistency

**Comment by claytondaley** [comment]
OK so this code hasn't been replaced yet?  I saw the not-Old build and assumed it had.  If you're not working in the `Old` file right now, I can do some light refactoring and add test cases.  At minimum, I'll get my arms around all of the syntax.  Maybe I'll stumble on an actual bug.

**Comment by Skibisky** [comment]
The .old GenRunes is probably gonna stick around for a while, it does all it needs to and isn't the slowest part of the run.

**Pull request closed without merging**
