### PR TITLE
Clear Progress on Loadout Removal

### LINKED ISSUE #79: Remove "Done" from Build if Loadout is Deleted
Very minor but noting things that I might find a way to easily fix.

### PR DESCRIPTION
**Pull request by claytondaley**
Resolves #79 by clearing the "Progress" panel on the build column if the associated loadout is removed.

### CODE REVIEW

**Comment by claytondaley** [comment]
hmm don't merge this yet.  i may have broken something

**Comment by claytondaley** [comment]
Hmm.  The code looks fine but I had it fail to unlock some runes.  The "locked" monsters were also unable to build their 6 runes (inexplicably).

**Comment by claytondaley** [comment]
How are "locked" builds handled?  Do we need to remove them from loadouts but not unlock the runes?

**Comment by claytondaley** [comment]
OK I can't reproduce my problem.  Perhaps it wasn't merged with the PR that unlocks the runes.

**Comment by claytondaley** [comment]
I've tested this PR and #98 locally and they're looking good.  I suggest merging both and getting a release out.

**Review by Skibisky — APPROVED** [review]

**Pull request merged**
